### ISSUE TITLE
duplicate DLM attachment in media library

### ISSUE THREAD

**Issue by mplusb** [WPChill/download-monitor#1001]
**Describe the bug**
When I add a download it also appears in the media library itself. Is there any reason this happens? The object that gets shown there only displays the DLM placeholder and a filepath that doesn't work (as the file is safely in the dlm_uploads folder and not anywhere in the standard uploads folder). I can even delete these objects from the media library and the downloads of course still work. Therefore why are these here and how can i stop them appearing in the media library? The problem these cause is that a) it clutters the media library and b) the media library objects are returned by our custom search (even though you can't get to the download its just not great from UI perspective). 

**To Reproduce**
1. Go to downloads > add a new download > upload a file 
2. go to media library
3. See the attachment created

**Extensions installed and activated:**
- [ ] Advanced Access Manager
- [ ] Amazon S3
- [ ] Buttons
- [ ] Captcha
- [ ] CSV Exporter
- [ ] CSV Importer
- [ ] Downloading Page
- [ ] Email lock
- [ ] Email Notifications
- [ ] Google Drive
- [ ] Gravity Forms
- [ ] Mailchimp
- [ ] Ninja Forms
- [ ] Page Addon
- [ ] Terms & Conditions
- [ ] Twitter Lock

**Additional context**
tried with 4.5.5 as well to see if it's a new bug, it happens with that version as well.

**Comment by razvanaldea89** [comment]
This is the way this plugin was designed to work, to create attachments with the files uploaded with Download Monitor and hide them behind a placeholder. Although they appear in the Media Library, so that they can be selected/deleted/searched, they can not be viewed because they are in the `dlm_uploads` protected folder. If you delete the files the downloads still work in the sense that you can download a file with the same name and type but you won't be able to open it because it will be corrupted.

**Comment by cristianraiber** [comment]
We should consider a solution for this @giucu91

**Comment by razvanaldea89** [comment]
Media Library now has filters for Download Monitor files and is not showing files uploaded through Download Monitor by default.
