### ISSUE TITLE
Allowed URL schemes bug

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1035]
In case of a localhost server the download file url is changed into 'C:/Users/Teo Alex/Local Sites/dlm/app/public/wp-content/uploads/dlm_uploads/' and the download from "C" scheme is not allowed.

**Comment by razvanaldea89** [comment]
Currently we are only allowing Downloads from http, https, fts & ftps as URL schemes to be downloaded, but in the scenario @TeoAlex is mentioning the Windows OS says the file is from `C:/...` ( on servers I don't think this is the case, but localhost development on Windows is stalled ), thus giving the `Access denied` output. Maybe we should do like the restricted extensions and define a restricted schemes variable from downloading ( also add a filter so that users can add their own ), and if some exploits appear in time populate the above mentioned variable.

@TeoAlex @giucu91 @cristianraiber any thoughts on this one?
