### ISSUE TITLE
download is not allowed for this file type

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#1196]
**Describe the bug**
 Downloads that previously used to work no longer work: The cause is that I use a URL that points to the actual download. That url uses a parameter rather than a filename with extension.

This does not work (screenshot)
![image](https://user-images.githubusercontent.com/84579642/214535152-40935d5d-67c5-4503-96e8-58762a4e3edd.png)

This does work:
![image](https://user-images.githubusercontent.com/84579642/214535199-eeec0a90-c8e7-4e72-98a0-71a8d7e1f522.png)

https://secure.helpscout.net/conversation/2133420829/53774?folderId=4656047

**Comment by razvanaldea89** [comment]
Because we are checking for file extensions for security reasons, even on remote servers, files with extension .php, .html, .htm & .tmp won't be allowed download. With version 4.7.75 of the plugin we've added a filter, `dlm_check_remote_extension` that can bypass the extension check for remote files. So, adding :

`add_filter( 'dlm_check_remote_extension', '__retun_false' );` in the child theme's functions.php file will bypass the check.

Going to close this issue.
