### ISSUE TITLE
Members only modal improvents

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/download-monitor#1593]
![image](https://github.com/user-attachments/assets/7b9aa3f7-1052-4fdc-ab0c-85abdeeeec5a)
Using: No Access Modal -> ON; Use default modal -> OFF
- [x] Too much white space
- [x] Needs some padding for inputs
- [x] Should move the close button to the top right and make it an X ( also maybe close modal on outside click/ on esc key )
- [ ] Can the download start automatically after i log-in?

**Comment by razvanaldea89** [comment]
The close button is from a template from Tailwind, don't think it's a good idea to move it, we should follow the same rules, as the other locking system use the same close button display. The close on outside click/esc key is valid, will implement it.

We'll output the download link, so that if it's locked with another locking system a new modal will appear when the user clicks the download link.
