### ISSUE TITLE
FileSize quirks

### ISSUE THREAD

**Issue by TotteKarlsson** [WPChill/download-monitor#173]
Hi,
I'm using the download monitor version 1.4.3. First, seem to be a great plugin and I am planning using it for all my websites.

Currently I am using to host some (binary) zip files. I keep the zipfiles under a folder ~/downloads and put them there manually and give the download monitor (DM) the path when setting up the download. 

When doing so, it seems the DM records the size of the file and uses that later on when a client downloads the file. Until here everything works perfect.

If I manually update the physical file, however, to a new file, with different size, the download will no longer work properly, cause in the download logic there seem to be usage of the 'initial' size of the 'original' download used. Is that correct?

Question is, is there any way to 'update', refresh these numbers? I can understand that one should set up a 'new version' when changing the physical file, but sometimes it is practical just to update the physical file itself. 

Or can I modify the code to ignore the filesize and just copy whatever is on disk?

Cheers,
Totte

**Comment by barrykooij** [comment]
Hey Totte,

Currently the only way to recalculate the file size would be to add a new version. I understand that there might be scenarios where it's more convenient to just upload a new file via FTP so I'll l keep this issue logged for future improvements but there aren't any plans to do this any time soon.

**Comment by maticomp** [comment]
Hey Barry,

Are there any plans on attending this issue? I was going to report the exact some problem now but found this issue.

Is there any particular reason why DM is sending `$version->filesize` in the `Content-Length` header instead of simply `filesize()` output?

While in all other places basically only display/informational metadata would be affected, any error in this place results in failed downloads on many browsers.

Fortunately, fixing this using simple custom made plugin is not a big issue, but I'm curious about the design decision here.

Cheers,
Mateusz

**Comment by jamesgol** [comment]
I'd like to +1 this issue.  At some point someone modified some files and just uploaded new versions instead of adding a new version.  Unfortunately it would send the wrong filesize to the client and the browser wasn't happy.

**Comment by cristianraiber** [comment]
Kind of late to the party here, but I think this has been addressed w/ newer versions of DLM. Can anyone test and reply back here if you're still running into issues? I'll close this ticket for now as it's quite old, but will re-open if any of y'all comment back w/ issues found. 

Thanks so much!
