### ISSUE TITLE
Set custom title on shortcode basis

### ISSUE THREAD

**Issue by hchouhan** [WPChill/download-monitor#644]
We need a parameter in the shortcode to customize the title of the download

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1309822313/12653/

**Comment by cristianraiber** [comment]
More info: 

Hi, I have previously posted this question on your forum but that seems to not get much activity... I'm therefore following the suggestion on your website which says to contact you this way for support. This is more of a question I suppose than a problem report. My question is: I'm using Download Monitor (and have also purchased Advanced Access Manager) how can I "easily" modify the text of the link displayed? I'm using the default template (displays Title with NO version information as a link) however I link to my download from many pages in my site - depending on context of the linking page I want to vary the text - in one place "Download" in other place "My Product Name" etc... As they all point to the same download is there a way to "easily" change the text of the download? What would be nice is something like: [download id="1234" link_text="Download"] I know that I could create a new Download (e.g. id=1235) which had a different title however that would result in logging differently and seems like over-kill when really all I want is to change the link text. Is this already possible with the plugin? If not, would you consider this as a feature request for a future version? By the way the plugin works great and I'm otherwise very happy with it but this one little tweak would be so helpful!

**Comment by cristianraiber** [comment]
This actually works, but it needs the DLM Buttons extension.
