### ISSUE TITLE
htaccess/nginx rules for protecting the wp-content/uploads/dlm_uploads/ folder

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/download-monitor#725]
https://secure.helpscout.net/conversation/1542002522/38715

**Comment by giucu91** [comment]
Create a button in Settings -> Advanced -> Miscellaneous for regenerating protection for uploads folder. Also it'll be nice to have some checkmarks to inform user if he have a .htaccess or a index.html file.

Function to create htaccess is here : https://github.com/WPChill/download-monitor/blob/master/src/Installer.php#L247

**Comment by cristianraiber** [comment]
@giucu91 - I don't think we should keep doing this IF we change the way we start downloads.

**Comment by TeoAlex** [comment]
For nginx we don't create a file that prevents direct access to the files in the dlm_uploads folder. DLM adds a notification for the user with instructions to add a rule in the nginx  server configuration (just like EDD).

**Comment by razvanaldea89** [comment]
@TeoAlex please merge this in branch 4.5.5 after the 4.5.4 release

**Comment by razvanaldea89** [comment]
Update field type htaccess_status so that :
- it will disable the regenerate htaccess buton if server is NGINX
- will display info about what to do if server is NGINX
- field class now accepts only 1 argument, the `$option`, that will be divided inside the class
- after the regeneration process is done the redirect will head towards the Misc tab of the Settings
