### ISSUE TITLE
Conflict with Intuitive Custom Post Order plugin

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#809]
I’m facing a conflict with the plugin https://wordpress.org/plugins/intuitive-custom-post-order/. When active for Downloads CPT, the Dashboard widget is not sorted by downloads count, thus the downloads bars get crazy – they tend to run out of the widget space.

From what I’ve gathered from the code, the bar width is computed as a current count/max. count ratio, while the max count is taken from the first item. It works fine, when the items are ordered by the downloads count. But when Simple CPO is active, the widget is ordered by the menu order (probably). When the first item has 5 downloads and second 1500, you can imagine what’s going to happen…

https://wordpress.org/support/topic/conflict-with-intuitive-custom-post-order-plugin/

**Comment by black-eye** [comment]
Hello, original poster from WP forum here. I'm here to add extra info. 

The problem seems to be caused by the fact that the Simple CPO plugin seems to interfere with the query here: https://github.com/WPChill/download-monitor/blob/e665c700cf6971f753d3577805924bc258edffc9/src/Admin/Dashboard.php#L37 
The downloads should be ordered by their count number, starting with the highest. Simple CPO somehow manages to override this query and order it by the menu order.

I have one very old version of the site using DLM 1.9.9, which works fine even with SimpleCPO. 
The query and the whole aproach is quite different there:
```
$args = array(
     'post_status'    => 'publish',
     'post_type'      => 'dlm_download',
     'no_found_rows'  => 1,
     'posts_per_page' => 10,
     'orderby'        => 'meta_value_num',
     'order'          => 'desc',
     'meta_query'     => array(
          array(
               'key'     => '_download_count',
               'value'   => '0',
               'compare' => '>'
          )
     ),
     'meta_key'       => '_download_count',
     'fields'         => 'ids'
);

$download_ids = get_posts( $args );
``` 
The changes to this part started to come somewhere around this commit: https://github.com/WPChill/download-monitor/commit/aba842bee3340d300e113759b9874a8cd5d6f7af?diff=split

Hope it will help.

**Comment by giucu91** [comment]
Hello @black-eye do you have enabled ordering for Downloads ?

**Comment by TeoAlex** [comment]
We have identified the issue, unfortunately we can't fix it because we cannot prevent "Intuitive Custom Post Order" plugin from meddleing with the WP_query regarding dashboard's "Pupular Downloads" widget.

**Comment by cristianraiber** [comment]
@razvanaldea89 - we need help w/ this one

**Comment by razvanaldea89** [comment]
Should be OK now with the majority of plugins that use the `pre_get_posts` action to order the posts.

**Comment by black-eye** [comment]
> Should be OK now with the majority of plugins that use the `pre_get_posts` action to order the posts.

Excellent, everything is ok now.
