### ISSUE TITLE
in Firefox, PDF downloads are no longer being forced to the user

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#871]
**Describe the bug**
Since the recent update (Version 4.5.5), in Firefox, PDF downloads are no longer being forced to the user, but instead are being opened by the browser. I have confirmed that "Redirect to file" is not enabled. Also, according to my testing, PDF downloads are still forced in Chrome, Opera and Edge. Since some of my site's users use Firefox, please fix this bug so that downloads in Firefox are once again forced to the user, as specified in your documentation: "By default, downloads are forced to the user. This means the user will be prompted to pick a location for the file on their computer and the file will download to it."

https://zachary-jones.com/zambombazo/clozeline-juanes-alessia-cara-querer-mejor/

Click on the pdf link on that page labeled "Clozeline: Juanes, Alessia Cara - Querer mejor".

https://secure.helpscout.net/conversation/1814412979/45297?folderId=4656047

**Screenshots**

https://user-images.githubusercontent.com/84579642/158355115-a7639952-3118-4137-975e-3554039930f6.mp4

**Comment by razvanaldea89** [comment]
@beatricelucaci my Firefox is downloading the PDF as before, no problems. This is not a DLM issue rather than a Firefox issue and how the user has setup the browser.
@giucu91 @TeoAlex can you test this also?

**Comment by TeoAlex** [comment]
Tested with Firefox Dev and Firefox and the file is NOT downloaded but opened in a new tab. The issue is that in mozila browsers the default setting for PDF files is to open them in browser.

I have found a way we can "trick" the browser into downloading the file.  If we set the header to `'Content-Type: application/octet-stream'` the PDF will download.  The mime-type in DLM is set here https://github.com/WPChill/download-monitor/blob/4.5.9/src/DownloadHandler.php#L618 and overwritten based on file type in the foreach below.

Any ideeas about this solution @giucu91 @razvanaldea89 ?

**Comment by razvanaldea89** [comment]
The problem with the 'Content-Type: application/octet-stream' is that after you download the PDF file the browser automatically opens the file in the browser, which is somewhat annoying and don't think it's a good implementation

**Comment by razvanaldea89** [comment]
For the moment it seems there is no solution that comes with no compromise, so we'll leave it be until the right one comes. The solutions found, after the download, immediately opens the PDF file in the browser if the user has chosen to open the PDF files in the build in PDF viewer of the browser.
