### ISSUE TITLE
conflict with WPML-  link only for the original languages

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/download-monitor#969]
**Describe the bug**
 I use the free version of your great tool for a website which has 2 languages with wpml. We use 2 different URLs for the languages. We want the downloads to be accessible in both languages. Unfortunately this is not possible when the url for the language changes, your plugin offers the link only for the original languages. When we turn off security it works, but we need to have the files protects. 

https://secure.helpscout.net/conversation/1909009250/47317?folderId=4656047

**Comment by razvanaldea89** [comment]
`We just found out, that it works when the URL to the file is set relatively in the download post. So when we correct the urls of all download manually it works. But you might consider this for future development.` - client foundings

**Comment by TeoAlex** [comment]
The relative URL to the file in the download post problem is fixed in the newer versions of DLM.

For older downloads the simple solution is to manualy modify the download URL or on newer versions of DLM simply clicking "Update" in the download posts solves the problem.

We should not try and automaticaly fix this by making changes in the database because we are depending on a lot of variables.

**Comment by razvanaldea89** [comment]
This is fixed starting from 4.7.54
